name: Build and Test Go Application

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test Go Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: true

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build -v ./...

      - name: Run Tests with Coverage
        run: |
          go test -coverprofile=coverage.out -v ./...
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total Coverage: $coverage%"
    
          min_coverage=80.0
          if (( $(echo "$coverage < $min_coverage" | bc -l) )); then
            echo "Test coverage is below ${min_coverage}%. Failing the workflow."
            exit 1
          fi

      - name: Check Formatting using go fmt
        run: |
          unformatted=$(gofmt -s -l .)
          if [[ -n "$unformatted" ]]; then
            echo "Code is not formatted. Run 'gofmt -s -w .' to fix."
            echo "$unformatted"
            exit 1
          fi
